### ISSUE TITLE
Mulitple instances seem to be not supported

### ISSUE THREAD

**Issue by davidedmundson** [cerebrate/notify_mqtt#1]
Good work making this, one minor issue. I have a config:

```
notify:
  - name: laptop
    platform: notify_mqtt
    topic: david-laptop/notify

notify:
  - name: pc
    platform: notify_mqtt
    topic: david-desktop/notify
```

only the latter one appears. After swapping it's still only the latter one.

**Comment by cerebrate** [comment]
Hm. I hadn't tried this myself (it started out as a quick hack, so probably isn't the best written ever). I'll give it a look and see wha needs tweaking.

**Comment by sumnerboy12** [comment]
This is working for me. Try adjusting your config to;

```
notify:
  - name: laptop
    platform: notify_mqtt
    topic: david-laptop/notify
  - name: pc
    platform: notify_mqtt
    topic: david-desktop/notify
```
